
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Pooled (pgbouncer transaction mode) — fine for the app at runtime.
    url: env("DATABASE_URL"),
    // Unpooled — required for migrate/db push, which need a session-level
    // advisory lock the transaction pooler can't hold. Omitting this here
    // silently discards schema.prisma's own directUrl and makes migrate/push
    // hang against the pooler instead of failing fast.
    directUrl: env("DIRECT_URL"),
  },
});
